services:
  backend:
    build: ./backend
    ports:
      - "60006:3000"
    volumes:
      - ./backend/sqlio.sqlite:/app/sqlio.sqlite
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "60005:80"
    depends_on:
      - backend
    restart: unless-stopped
